version: "3.7"

services:
    mysql:
        image: mysql:8.0
        networks:
            - personal-network
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
    redis:
        image: "redis:alpine"
        command: redis-server --requirepass password
        ports:
            - "6379:6379"
        volumes:
            - $PWD/redis-data:/var/lib/redis
            - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
        environment:
            - REDIS_REPLICATION_MODE=master
        networks:
            personal-network:
    mailhog:
        image: mailhog/mailhog
        ports:
            - 1025:1025
            - 8025:8025
networks:
    personal-network:
